apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - name: myapp
      image: ttl.sh/renn-amm:2h
      ports:
        - containerPort: 4444
      livenessProbe:
        httpGet:
          path: /
          port: 4444
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 4444
        initialDelaySeconds: 5
        periodSeconds: 10
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
